name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      env:
        REGISTRY_USER: ${{ secrets.DOCKERHUB_USER }}
        REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: bash .ci/build-and-push.sh
